apiVersion: v1
kind: ServiceAccount
metadata:
  name: smoketest-sa
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: smoketest-rolebinding
subjects:
- kind: ServiceAccount
  name: smoketest-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
data:
  test.sh: |
    #!/bin/sh
    echo "Get pods:"
    /usr/local/bin/kubectl get pods -o wide
    echo "Get services:"
    /usr/local/bin/kubectl get services -o wide
    echo "Get config-maps:"
    /usr/local/bin/kubectl get cm -o wide
    echo "Get nodes:"
    /usr/local/bin/kubectl get node -o wide
  test_pod.sh: |
    #!/bin/sh
    echo "Creating deployment:"
    /usr/local/bin/kubectl run nginx --image=nginx --namespace ${MY_NAMESPACE}
    echo "Sleeping ..."
    sleep 10
    echo "Get deployment:"
    /usr/local/bin/kubectl get deployment nginx --namespace ${MY_NAMESPACE}
    echo "Delete deployment:"
    /usr/local/bin/kubectl delete deployment nginx --namespace ${MY_NAMESPACE}
kind: ConfigMap
metadata:
  name: smoke-test-config
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: smoketests.smoketest.k8s.io
spec:
  group: smoketest.k8s.io
  names:
    kind: SmokeTest
    listKind: SmokeTestList
    plural: smoketests
    singular: smoketest
    shortNames:
    - smkt
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smoke-test-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: smoke-test-operator
  template:
    metadata:
      labels:
        name: smoke-test-operator
    spec:
      serviceAccountName: smoketest-sa
      containers:
        - name: smoke-test-operator
          env:
            - name: MY_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: shrinand/smoke-test-operator:latest
          command:
          - smoke-test-operator
          imagePullPolicy: Always
          volumeMounts:
          - name: smoke-tests
            mountPath: /smoke-tests
      volumes:
        - name: smoke-tests
          configMap:
            name: smoke-test-config
