apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: smoketests.smoketest.k8s.io
spec:
  group: smoketest.k8s.io
  names:
    kind: SmokeTest
    listKind: SmokeTestList
    plural: smoketests
    singular: smoketest
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smoke-test-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: smoke-test-operator
  template:
    metadata:
      labels:
        name: smoke-test-operator
    spec:
      containers:
        - name: smoke-test-operator
          image: sjavadekar/smoke-test-operator-base:latest
          command:
          - smoke-test-operator
          imagePullPolicy: Always
